-- Crear tabla BRANDS
CREATE TABLE BRANDS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    STATE BOOLEAN NOT NULL
);

-- Crear tabla PRODUCTS
CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    STATE BOOLEAN NOT NULL
);