ALTER TABLE PRICES
ADD CONSTRAINT fk_prices_brand_id
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID);

ALTER TABLE PRICES
ADD CONSTRAINT fk_prices_product_id
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID);